basePath: /
definitions:
  handler.LogoutOutputModel:
    properties:
      is_logout:
        type: boolean
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  user.GoogleOAuth2Code:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  user.TokenAccessModel:
    properties:
      access_token:
        type: string
    required:
    - access_token
    type: object
  user.TokenRefreshModel:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  user.UserJSONBModel:
    properties:
      date_birth:
        type: string
      gender:
        type: boolean
      name:
        type: string
      nickname:
        type: string
      patronymic:
        type: string
      phone:
        type: string
      surname:
        type: string
    required:
    - name
    - nickname
    - surname
    type: object
  user.UserLoginModel:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  user.UserRegisterModel:
    properties:
      data:
        $ref: '#/definitions/user.UserJSONBModel'
      email:
        type: string
      password:
        type: string
    required:
    - data
    - email
    - password
    type: object
host: localhost:5000
info:
  contact: {}
  title: Geo-organizer Main Server
  version: "1.0"
paths:
  /auth/activate:
    get:
      consumes:
      - application/json
      description: Активация аккаунта по почте
      operationId: activate
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/handler.LogoutOutputModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Activate
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Выход из аккаунта
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/handler.LogoutOutputModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Logout
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Обновление токена доступа и токена обновления
      operationId: refresh
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.TokenRefreshModel'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/user.TokenAccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Refresh
      tags:
      - auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.UserLoginModel'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/user.TokenAccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignIn
      tags:
      - auth
  /auth/sign-in/oauth2:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя через Google OAuth2
      operationId: login_oauth2
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.GoogleOAuth2Code'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/user.TokenAccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignInOAuth2
      tags:
      - auth
  /auth/sign-in/vk:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя через VK
      operationId: login_vk
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.UserLoginModel'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/user.TokenAccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignInVK
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Регистрация пользователя
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.UserRegisterModel'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            $ref: '#/definitions/user.TokenAccessModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
